### ISSUE TITLE
Bad escaped character in JSON

### ISSUE THREAD

**Issue by fredgie7** [netsuite-upload-org/netsuite-upload#85]
a suiteScript file that works fine with its corresponding restlet won't push up to netsuite. pull works fine.

my local node version is v16.15.1

ERROR uploading file. | Unknown Error: | HTTP Status: undefined | HTTP Error: Bad escaped character in JSON at position 203 | Local Stack: | SyntaxError: Bad escaped character in JSON at position 203
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (c:\Users\Fred\.vscode\extensions\nsupload-org.netsuite-upload-1.2.4\node_modules\superagent\lib\node\parsers\json.js:14:31)
    at Stream.emit (node:events:513:28)
    at Unzip.<anonymous> (c:\Users\Fred\.vscode\extensions\nsupload-org.netsuite-upload-1.2.4\node_modules\superagent\lib\node\unzip.js:53:12)
    at Unzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by mikebell98** [comment]
Getting this exact error too.
